kong:
  image: mashape/kong
  links:
    - kong-db:kong-database
#    - service:testservice
  environment:
    - DATABASE=postgres
  ports:
    - "80:8000"
    - "443:8443"
    - "8001:8001"
    - "7946:7946"
    - "7946:7946/udp"

kong-db:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong
  expose:
    - "5432"

#service:
#  image: slidewiki/deckservice
#  environment:
#    - APPLICATION_PORT=80
#    - VIRTUAL_HOST=testservice.localhost
#  expose:
#    - "80"
